# Generated by Django 5.0.6 on 2024-06-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoría')),
                ('nombreCategoria', models.CharField(max_length=150, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('producto', models.CharField(max_length=80, verbose_name='nombre del producto')),
                ('detalles', models.CharField(blank=True, max_length=300, null=True, verbose_name='detalles del producto')),
                ('imagen', models.ImageField(default='nn.jpg', upload_to='images/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
